# Generated by Django 5.1.5 on 2025-04-15 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('photo_url', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('hotel', 'Hotel'), ('gym', 'Gym'), ('other', 'Other')], default='home', max_length=10)),
                ('custom_type', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField()),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('more_info', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('postal_code', models.IntegerField(default=123)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='hy', max_length=100)),
                ('subtitle', models.CharField(default='hey', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('address_type__in', ['home', 'work', 'hotel', 'gym', 'other'])), name='valid_address_type'), models.CheckConstraint(condition=models.Q(models.Q(('address_type', 'other'), ('custom_type__isnull', False), models.Q(('custom_type', ''), _negated=True)), ('address_type__in', ['home', 'work', 'hotel', 'gym']), _connector='OR'), name='valid_address_type__custom_type')],
            },
        ),
    ]
