from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(Menu)
admin.site.register(MenuItem)
admin.site.register(Product)
admin.site.register(Deal)
admin.site.register(Cancellation)
admin.site.register(DealProduct)
admin.site.register(Category)
admin.site.register(Favorite)
admin.site.register(CustomizationHeader)
admin.site.register(CustomizationChoice)
admin.site.register(CustomizationPriceRule)
admin.site.register(ProductCustomizationHeader)
admin.site.register(ProductChoicesUnavailablility)
admin.site.register(Tags)
admin.site.register(ProductTags)
admin.site.register(ExpandableHeader)
admin.site.register(ExpandableChoices)
admin.site.register(Branch)
admin.site.register(DealBranchStock)
admin.site.register(ProductBranchStock)
admin.site.register(Offer)
admin.site.register(CartItem)
admin.site.register(Cart)
admin.site.register(CartOffer)
admin.site.register(CartItemCustomization)
admin.site.register(PaymentMethod)
admin.site.register(Transaction)
admin.site.register(CarouselCard)
admin.site.register(CarouselSchedule)
admin.site.register(Invoice)
admin.site.register(Order)
admin.site.register(OrderItem)
admin.site.register(OrderOffer)
admin.site.register(UserOfferUsage)
admin.site.register(SpecialSuggestionsBranchWise)